In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
dataset = pd.read_csv('datakelulusanmahasiswa.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [60]:
print(x)

[['ANIK WIDAYANTI' 28 2.76 2.8 3.2 3.17 2.98 3.0 3.03 nan 3.07]
 ['DWI HESTYNA PRIHASTANTY' 32 3.0 3.3 3.14 3.14 2.84 3.13 3.25 nan 3.17]
 ['MURYA ARIEF BASUKI' 29 3.5 3.3 3.7 3.29 3.53 3.72 3.73 nan 3.54]
 ['NANIK SUSANTI' 27 3.17 3.41 3.61 3.36 3.48 3.63 3.46 nan 3.41]
 ['RIFKA ISTIQFARINA' 29 2.9 2.89 3.3 2.85 2.98 3.0 3.08 nan 3.09]
 ['SUHARYONO' 27 2.95 2.82 3.09 3.1 2.78 3.16 3.23 nan 3.07]
 ['FARIKHATUN NAZLI' 26 2.76 3.14 2.6 2.95 3.23 3.33 3.3 3.3 3.06]
 ['FIFI SUNALISA' 27 2.62 2.89 2.32 2.5 2.5 2.86 3.05 2.5 2.91]
 ['HENDRIK MULIYANTO' 25 3.6 3.54 3.52 3.39 3.52 3.68 3.15 nan 3.4]
 ['IMAM AGUNG RIBOWO' 28 2.71 2.55 1.77 2.11 1.93 2.13 1.78 0.2 2.2]
 ['IMAM SANTOSA' 27 3.14 3.46 3.4 3.43 3.27 3.15 3.81 4.0 3.44]
 ['IRFAN EKO WAHYUDI' 32 2.67 2.3 1.57 1.44 1.58 1.68 1.13 0.94 2.4]
 ['IWAN HAMBALI' 26 2.57 2.82 2.2 2.45 2.1 2.42 1.0 1.42 2.45]
 ['M SYAIFULLAH' 31 2.71 3.0 2.65 2.27 2.13 3.34 2.5 nan 2.57]
 ['DIANA LAILY FITHRI' 26 3.24 3.38 3.44 3.3 3.56 3.45 3.35 3.35 3.45]
 [

In [61]:
print(y)

['TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TEPAT' 'TEPAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT' 'TERLAMBAT'
 'TERLAMBAT']


In [64]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:11])
x[:, 1:11] = imputer.transform(x[:, 1:11])

In [65]:
print(x)

[['ANIK WIDAYANTI' 28.0 2.76 2.8 3.2 3.17 2.98 3.0 3.03 2.063 3.07]
 ['DWI HESTYNA PRIHASTANTY' 32.0 3.0 3.3 3.14 3.14 2.84 3.13 3.25 2.063
  3.17]
 ['MURYA ARIEF BASUKI' 29.0 3.5 3.3 3.7 3.29 3.53 3.72 3.73 2.063 3.54]
 ['NANIK SUSANTI' 27.0 3.17 3.41 3.61 3.36 3.48 3.63 3.46 2.063 3.41]
 ['RIFKA ISTIQFARINA' 29.0 2.9 2.89 3.3 2.85 2.98 3.0 3.08 2.063 3.09]
 ['SUHARYONO' 27.0 2.95 2.82 3.09 3.1 2.78 3.16 3.23 2.063 3.07]
 ['FARIKHATUN NAZLI' 26.0 2.76 3.14 2.6 2.95 3.23 3.33 3.3 3.3 3.06]
 ['FIFI SUNALISA' 27.0 2.62 2.89 2.32 2.5 2.5 2.86 3.05 2.5 2.91]
 ['HENDRIK MULIYANTO' 25.0 3.6 3.54 3.52 3.39 3.52 3.68 3.15 2.063 3.4]
 ['IMAM AGUNG RIBOWO' 28.0 2.71 2.55 1.77 2.11 1.93 2.13 1.78 0.2 2.2]
 ['IMAM SANTOSA' 27.0 3.14 3.46 3.4 3.43 3.27 3.15 3.81 4.0 3.44]
 ['IRFAN EKO WAHYUDI' 32.0 2.67 2.3 1.57 1.44 1.58 1.68 1.13 0.94 2.4]
 ['IWAN HAMBALI' 26.0 2.57 2.82 2.2 2.45 2.1 2.42 1.0 1.42 2.45]
 ['M SYAIFULLAH' 31.0 2.71 3.0 2.65 2.27 2.13 3.34 2.5 2.063 2.57]
 ['DIANA LAILY FITHRI' 26.0

In [66]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [67]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 28.0 2.76 2.8 3.2 3.17 2.98 3.0 3.03 2.063 3.07]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 32.0 3.0 3.3 3.14 3.14 2.84 3.13 3.25 2.063 3.17]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 29.0 3.5 3.3 3.7 3.29 3.53 3.72 3.73 2.063 3.54]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 27.0 3.17 3.41 3.61 3.36 3.48 3.63 3.46 2.063 3.41]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 29.0 2.9 2.89 3.3 2.85 2.98 3.0 3.08 2.063 3.09]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 27.0 2.95 2.82 3.09 3.1 2.78 3.16 3.23 2.063 3.07]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 26.0 2.76 3.14 2.6 2.95 3.23 3.33 3.3 3.3 3.06]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 27.0 2.62 2.

In [68]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [69]:
print(y)

[1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1]


In [70]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [71]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 29.0 3.5 3.3 3.7 3.29 3.53 3.72 3.73 2.063 3.54]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 26.0 3.24 3.38 3.44 3.3 3.56 3.45 3.35 3.35 3.45]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 29.0 2.9 2.89 3.3 2.85 2.98 3.0 3.08 2.063 3.09]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 27.0 2.71 3.27 2.54 3.36 3.23 3.28 3.15 2.0 3.19]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 27.0 2.62 2.89 2.32 2.5 2.5 2.86 3.05 2.5 2.91]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 32.0 3.0 3.3 3.14 3.14 2.84 3.13 3.25 2.063 3.17]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 31.0 2.71 3.0 2.65 2.27 2.13 3.34 2.5 2.063 2.57]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 28.0 2.76 2.8 

In [72]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 27.0 3.17 3.41 3.61 3.36 3.48 3.63 3.46 2.063 3.41]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 27.0 2.86 2.86 2.45 1.86 3.19 3.14 2.98 2.0 3.04]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 26.0 2.76 3.14 2.6 2.95 3.23 3.33 3.3 3.3 3.06]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 27.0 3.14 3.46 3.4 3.43 3.27 3.15 3.81 4.0 3.44]]


In [73]:
print(y_train)

[1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]


In [74]:
print(y_test)

[1 1 0 1]


In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [76]:
print(x_train)

[[0.0 0.0 0.0 -0.2672612419124243 0.0 -0.2672612419124243
  -0.2672612419124243 0.0 -0.2672612419124243 -0.2672612419124244
  -0.2672612419124244 0.0 -0.2672612419124244 -0.2672612419124244
  -0.26726124191242434 3.7416573867739404 0.0 -0.2672612419124243
  -0.2672612419124244 0.38609367125267247 1.9778122831124232
  1.014997277393135 1.4444417175875517 0.9049859784704201
  1.3016672590078404 1.3661565390059642 1.1701701563299312
  0.2902685997516879 1.44723897963748]
 [0.0 0.0 0.0 3.7416573867739404 0.0 -0.2672612419124243
  -0.2672612419124243 0.0 -0.2672612419124243 -0.2672612419124244
  -0.2672612419124244 0.0 -0.2672612419124244 -0.2672612419124244
  -0.26726124191242434 -0.2672612419124243 0.0 -0.2672612419124243
  -0.2672612419124244 -1.061757595944848 1.141210558151636
  1.226455043516705 1.0847148530542532 0.9212043651813591
  1.351475955143345 0.8916338989567228 0.7637125151915638
  2.09150142463318 1.2422261126374177]
 [0.0 0.0 0.0 -0.2672612419124243 0.0 -0.2672612419124243

In [77]:
print(x_test)

[[0.0 0.0 0.0 0.0 -0.5773502691896258 0.0 0.0 -0.5773502691896258 0.0 0.0
  0.0 -0.5773502691896258 0.0 0.0 0.0 0.0 1.7320508075688774 0.0 0.0
  0.5773502691896258 1.0628945990551184 0.8033482777887463
  1.1937663051642378 0.732701475699828 1.6757946081328192
  1.6011937209662281 0.24251866272383008 -0.9187387115537634
  0.9178811204042068]
 [0.0 0.0 0.0 0.0 1.7320508075688774 0.0 0.0 -0.5773502691896258 0.0 0.0
  0.0 -0.5773502691896258 0.0 0.0 0.0 0.0 -0.5773502691896258 0.0 0.0
  0.5773502691896258 -0.6944244713826777 -1.4919325158933883
  -1.1335764074248649 -1.656542466799611 -0.9161010524459414
  -0.8699398956430685 -1.3631221387580743 -0.9931592050643867
  -1.0509073697381468]
 [0.0 0.0 0.0 0.0 -0.5773502691896258 0.0 0.0 1.7320508075688774 0.0 0.0
  0.0 -0.5773502691896258 0.0 0.0 0.0 0.0 -0.5773502691896258 0.0 0.0
  -1.7320508075688774 -1.2613015908787413 -0.32342593001884656
  -0.8326269187279982 0.07964146474998174 -0.5585982027109397
  0.08825477202176099 -0.29269493777013